### ISSUE TITLE
Tinder cards inside ion-modal

### ISSUE THREAD

**Issue by cmellinas** [driftyco/ionic-ion-tinder-cards#28]
Hi,

I tried to use ionic tinder cards inside ion-modal. 
On browser it's perfect but on mobile it's very sluggish.

The same code in ion-pane run well on both.

Is there a solution to make it work inside ion-modal like in ion-pane?

Thanks,

**Comment by mlynch** [comment]
Hmm, I don't know why this would happen. Try master now as a ton of things got merged, some of which dealt with performance and event bubbling (which could be the culprit here)

**Comment by Ionitron** [comment]
Greetings @cmellinas!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
