### ISSUE TITLE
Missing files in example project

### ISSUE THREAD

**Issue by gercheq** [driftyco/ionic-ion-tinder-cards#40]
http://localhost:8100/js/ionic.swipecards.js
Failed to load resource: the server responded with a status of 404 (Not Found) 

http://localhost:8100/js/services.js
Failed to load resource: the server responded with a status of 404 (Not Found)

http://localhost:8100/js/controllers.js
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by yarnball** [comment]
I'm also having this issue. Any tips on this?

**Comment by Ionitron** [comment]
Greetings @gercheq!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
