### ISSUE TITLE
Minification troubles

### ISSUE THREAD

**Issue by loicknuchel** [driftyco/ionic-ion-tinder-cards#44]
Hi,

I've got some troubles at minification time...
The `aProvider` is not found... I didn't figure out (from now) which is the aProvider, still searching...

**Comment by Ionitron** [comment]
Greetings @loicknuchel!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
