### ISSUE TITLE
Draggable elements in card

### ISSUE THREAD

**Issue by OliverZiegler** [driftyco/ionic-ion-tinder-cards#50]
Adding a range slider in the card (or any other draggable element) will result in not being able to drag this element but only the card.
Is this a bug or shall cards not be able to hold (almost) every other element?

**Comment by Ionitron** [comment]
Greetings @OliverZiegler!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
