### ISSUE TITLE
Wrong code on the Tinder Cards (Official) Pen

### ISSUE THREAD

**Issue by lfv89** [driftyco/ionic-ion-tinder-cards#67]
http://codepen.io/ionic/pen/nxEdH

cardSwipedLeft() and cardSwipedRight() shouldn't be inside CardCtrl, but inside CardsCtrl.

**Comment by p-syche** [comment]
The creator of this issue is absolutely right. I'm not creating another, identical issue, but I would like to point out that as it is written right now (in the codePen and in Your code on gitHub) actions cardSwipedLeft() and cardSwipedRight() have absolutely no effect. They should be either moved to the CardsCtrl or the template should be re-written to have those actions called.
